# Generated by Django 4.0.4 on 2022-05-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_choice_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='language',
            field=models.CharField(default='', max_length=2),
        ),
    ]
